image: node:latest
image: docker:stable

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t lhms-app .
    - docker tag lhms-app:latest dtwilliams10/lhms
    - docker push dtwilliams10/lhms

#deploy-containers:
# stage: deploy
# script:
# - export DOCKER_HOST=tcp://192.168.1.105:2375
# - docker run -d -v ${PWD}:/usr/src/app -v /usr/src/app/node_modules -p 3000:3000 --name=lhms-app lhms-app;