stages:
 - build
 - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t lhms-app .
deploy: 
  stage: deploy
  script:
    - docker stop lhms-app
    - docker rm lhms-app
    - docker run -d -p 3000:3000 --name=lhms-app lhms-app;