stages:
 - build
 - pre-deploy
 - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t lhms-app .

pre-deploy:
  stage: pre-deploy
  script:
    - docker stop lhms-app
    - docker rm lhms-app
  allow_failure: true

deploy: 
  stage: deploy
  script:
    - docker run -d -e LETSENCRYPT_EMAIL=david.williams110913@gmail.com -e LETSENCRYPT_HOST=lhms.dtwilliams10.com -e VIRTUAL_HOST=lhms.dtwilliams10.com --name=lhms-app lhms-app;