stages:
  - build
  - sonarqube-check
  - deploy

test build job:
  image: docker:latest
  stage: build
  only:
    - develop@LHMS/app
  tags:
    - develop
  script:
    - docker build -f test.Dockerfile -t frontend .

sonarqube-check:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop

test deploy job:
  stage: deploy
  only:
    - develop@LHMS/app
  trigger:
    project: LHMS/LHMS
    branch: develop

prod build job:
  image: docker:latest
  stage: build
  only:
    - master@LHMS/app
  tags:
    - production
  script:
    - docker build -f prod.Dockerfile -t frontend .

prod deploy job:
  stage: deploy
  only:
    - master@LHMS/app
  trigger:
    project: LHMS/LHMS
    branch: master
