stages:
 - build
 - pre-deploy
 - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t lhms-app .

pre-deploy:
  stage: pre-deploy
    - docker stop lhms-app
    - docker rm lhms-app
  allow_failure: true

deploy: 
  stage: deploy
  script:
    - docker run -d -p 3000:3000 --name=lhms-app lhms-app;