stages:
 - build
 - deploy

test build job:
  image: docker:latest
  stage: build
  only:
    - develop@LHMS/app
  tags:
    - develop
  script:
    - docker build -f test.Dockerfile -t lhmsapp .

test deploy job:
  image:
    name: docker/compose:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
     - docker-compose -f "docker-compose.test.yml" up -d --build
  environment:
    name: staging
    url: https://test.lhms.dtwilliams10.com
  only:
    - develop@LHMS/app
  tags:
    - develop

prod build job:
    image: docker:latest
    stage: build
    only:
      - master@LHMS/app
    tags:
      - production
    script:
      - docker build -f prod.Dockerfile -t lhmsapp .

prod deploy job:
 image:
  name: docker/compose:latest
  entrypoint: ["/bin/sh", "-c"]
 stage: deploy
 script:
  - docker-compose -f "docker-compose.prod.yml" up -d --build
 environment:
  name: production
  url: https://lhms.dtwilliams10.com
 only:
  - master@LHMS/app
 tags:
  - production
