stages:
 - build
 - deploy

test build job:
  image: docker:latest
  stage: build
  only:
    - branches@dtwilliams10/LHMS-FrontEnd
  script:
    - docker build -f test.Dockerfile -t lhms-app .

test deploy job:
  image:
    name: docker/compose:1.22.0
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker network disconnect lhms-frontend_webappnetwork proxy
    - docker-compose -f "docker-compose.test.yml" down
    - docker-compose -f "docker-compose.test.yml" up -d --build
    - docker network connect lhms-frontend_webappnetwork proxy
  environment:
    name: staging
    url: https://test.lhms.dtwilliams10.com
  only:
    - branches@dtwilliams10/LHMS-FrontEnd

prod build job:
    image: docker:latest
    stage: build
    only:
      - branches@LHMS/LHMS-FrontEnd
    script:
      - docker build -f prod.Dockerfile -t lhms-app .

prod deploy job:
 image:
  name: docker/compose:1.22.0
  entrypoint: ["/bin/sh", "-c"]
 stage: deploy
 script:
  - docker network disconnect lhms-frontend_webappnetwork proxy
  - docker-compose -f "docker-compose.prod.yml" down
  - docker-compose -f "docker-compose.prod.yml" up -d --build
  - docker network connect lhms-frontend_webappnetwork proxy
 environment:
  name: staging
  url: https://lhms.dtwilliams10.com
 only:
  - branches@LHMS/LHMS-FrontEnd
