stages:
 - build
 - deploy

build:
  image: docker:latest
  stage: build
  script:
    #- docker login -u dtwilliams10 -p ty135907 dtwilliams10/lhms
    - docker build -t lhms-app .
    - docker stop lhms-app
    - docker rm lhms-app
    - ddocker run -d -p 3000:3000 --name=lhms-app lhms-app;