stages:
 - build
 - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t lhms-app .

deploy:
  image:
    name: docker/compose:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker network disconnect lhms-frontend_webappnetwork proxy
    - docker-compose down
    - docker-compose -f "docker-compose.yml" up -d --build
    - docker network connect lhms-frontend_webappnetwork proxy