stages:
 - build
 - deploy

test build job:
  image: docker:latest
  stage: build
  only:
    - develop@LHMS/app
  tags:
    - develop
  script:
    - docker build -f test.Dockerfile -t lhmsapp .

test deploy job:
    stage: deploy
    only:
    - develop@LHMS/app
    trigger:
      LHMS/app/test-deploy-pipeline.yml

prod build job:
    image: docker:latest
    stage: build
    only:
      - master@LHMS/app
    tags:
      - production
    script:
      - docker build -f prod.Dockerfile -t lhmsapp .

prod deploy job:
    stage: deploy
    only:
    - master@LHMS/app
    trigger:
      LHMS/app/prod-deploy-pipeline.yml
