# Use PnP for dependency management
nodeLinker: pnp

# Optional: Enable ESM loader if needed
pnpEnableEsmLoader: true

# Optional: Enable inlining of PnP data
pnpEnableInlining: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
